services:
  spark-master:
    image: apache/spark:3.5.4
    container_name: spark-master
    hostname: spark-master
    user: root
    ports:
      - "80:8080"
      - "7077:7077"
    environment:
      - SPARK_MASTER_HOST=spark-master
      - SPARK_MASTER_PORT=7077
      - SPARK_MASTER_WEBUI_PORT=8080
    entrypoint: 
      - "bash"
      - "-c"
      - "/opt/spark/sbin/start-master.sh && tail -f /dev/null"
    volumes:
      - ./data:/opt/spark/work-dir/spark-warehouse/data:rw

  spark-connect:
    image: apache/spark:3.5.4
    container_name: spark-connect
    hostname: spark-connect
    user: root
    ports:
      - "443:4040"
      - "15002:15002"
    depends_on:
      - spark-master
    volumes:
      - ./spark/spark-defaults.conf:/opt/spark/conf/spark-defaults.conf
      - ./spark/jars/spark-connect_2.12-3.5.4.jar:/opt/spark/jars/spark-connect_2.12-3.5.4.jar
      - ./data:/opt/spark/work-dir/spark-warehouse/data:rw
    command: 
      - "bash"
      - "-c"
      - "/opt/spark/sbin/start-connect-server.sh --jars /opt/spark/jars/spark-connect_2.12-3.5.4.jar && tail -f /dev/null"

  spark-worker:
    image: apache/spark:3.5.4
    container_name: spark-worker
    hostname: spark-worker
    user: root
    depends_on:
      - spark-master
    entrypoint:
      - "bash" 
      - "-c"
      - "/opt/spark/sbin/start-worker.sh spark://spark-master:7077 && tail -f /dev/null"
    volumes:
      - ./data:/opt/spark/work-dir/spark-warehouse/data:rw
