apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: spark-connect-ingress
  namespace: {{ .Values.metadata.namespace }}
spec:
 rules:
  - host: mounir.eastus.cloudapp.azure.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: spark-connect
            port:
              number: {{ .Values.sparkConnect.connectUIPort }}
