apiVersion: v1
kind: Service
metadata:
  name: spark-connect
  namespace: {{ .Values.metadata.namespace }}
spec:
  ports:
    - name: "{{ .Values.sparkConnect.connectUIPort }}"
      port: {{ .Values.sparkConnect.connectUIPort }}
      targetPort: {{ .Values.sparkConnect.targetConnectUIPort }}
    - name: "{{ .Values.sparkConnect.connectPort }}"
      port: {{ .Values.sparkConnect.connectPort }}
      targetPort: {{ .Values.sparkConnect.targetConnectPort }}
  selector:
    role: connect
  type: {{ .Values.general.serviceType }}
  clusterIP: None
